if(NOT DEFINED BUILD_DIR OR NOT DEFINED CONFIG OR NOT DEFINED PROBE OR NOT DEFINED EXPECT_SUCCESS)
    message(FATAL_ERROR "Architecture probe invocation is incomplete")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${BUILD_DIR}" --config "${CONFIG}" --target "${PROBE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
set(log "${output}\n${error}")
file(WRITE "${BUILD_DIR}/${PROBE}-${CONFIG}.log" "${log}")
if(EXPECT_SUCCESS)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Expected ${PROBE} to compile:\n${log}")
    endif()
else()
    if(result EQUAL 0)
        message(FATAL_ERROR "Forbidden include unexpectedly compiled: ${PROBE}")
    endif()
    # A failed compiler launch, linker or configuration is never negative-test evidence.
    if(NOT log MATCHES "(fatal error C1083|error C1189|fatal error:.*No such file|#error)")
        message(FATAL_ERROR "Failure was not a compiler include error:\n${log}")
    endif()
    if(NOT log MATCHES "${EXPECTED_HEADER}")
        message(FATAL_ERROR "Failure did not identify ${EXPECTED_HEADER}:\n${log}")
    endif()
endif()
