if(NOT DEFINED SOURCE_DIR OR NOT DEFINED TEST_DIR)
    message(FATAL_ERROR "Validator fixture invocation is incomplete")
endif()
file(REMOVE_RECURSE "${TEST_DIR}")
file(MAKE_DIRECTORY "${TEST_DIR}")
file(COPY "${SOURCE_DIR}/src" DESTINATION "${TEST_DIR}")
file(WRITE "${TEST_DIR}/CMakeLists.txt"
    "cmake_minimum_required(VERSION 3.28)\nproject(LayerValidationFixture NONE)\nadd_custom_target(check ALL COMMAND \"${CMAKE_COMMAND}\" -DODYSSEUS_SOURCE_ROOT=${TEST_DIR}/src -P \"${SOURCE_DIR}/cmake/ValidateLayerIncludes.cmake\" VERBATIM)\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${TEST_DIR}" -B "${TEST_DIR}/build"
    RESULT_VARIABLE configured OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT configured EQUAL 0)
    message(FATAL_ERROR "Could not configure validator control:\n${output}\n${error}")
endif()
function(check_build allowed label)
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${TEST_DIR}/build"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(APPEND "${TEST_DIR}/results.log" "${label}: exit ${result}\n${output}\n${error}\n")
    if(allowed AND NOT result EQUAL 0)
        message(FATAL_ERROR "Clean source validator failed:\n${output}\n${error}")
    elseif(NOT allowed)
        if(result EQUAL 0 OR NOT "${output}\n${error}" MATCHES "[Ii]nclude error")
            message(FATAL_ERROR "${label} did not produce an architecture include error:\n${output}\n${error}")
        endif()
    endif()
endfunction()
check_build(TRUE "Clean control")
# Add each violation AFTER configure: a configure-only scanner would miss these.
file(WRITE "${TEST_DIR}/src/sim/unguarded.h" "#pragma once\n")
check_build(FALSE "Unguarded header after configure")
file(REMOVE "${TEST_DIR}/src/sim/unguarded.h")
file(WRITE "${TEST_DIR}/src/sim/violation.cpp" "#include <SDL3/SDL.h>\n")
check_build(FALSE "Simulation SDL3 include after configure")
file(WRITE "${TEST_DIR}/src/sim/violation.cpp" "#include \"../luna/engine/layer.h\"\n")
check_build(FALSE "Simulation relative Engine include")
file(WRITE "${TEST_DIR}/src/sim/violation.cpp" "#include \"${TEST_DIR}/src/luna/engine/layer.h\"\n")
check_build(FALSE "Simulation absolute Engine include")
file(WRITE "${TEST_DIR}/src/sim/violation.cpp" "#define HEADER <SDL3/SDL.h>\n#include HEADER\n")
check_build(FALSE "Macro expanded include")
file(REMOVE "${TEST_DIR}/src/sim/violation.cpp")
file(WRITE "${TEST_DIR}/src/luna/engine/violation.cpp" "#include \"../../sim/layer.h\"\n")
check_build(FALSE "Luna relative Simulation include")
file(REMOVE "${TEST_DIR}/src/luna/engine/violation.cpp")
# US-025: Physics uses Core only.
file(WRITE "${TEST_DIR}/src/luna/physics/violation.cpp" "#include \"../engine/layer.h\"\n")
check_build(FALSE "Physics relative Engine include")
file(WRITE "${TEST_DIR}/src/luna/physics/violation.cpp" "#include \"sim/layer.h\"\n")
check_build(FALSE "Physics Simulation include")
file(WRITE "${TEST_DIR}/src/luna/physics/violation.cpp" "#include <SDL3/SDL.h>\n")
check_build(FALSE "Physics SDL3 include")
file(WRITE "${TEST_DIR}/src/luna/physics/unguarded.h" "#pragma once\n")
check_build(FALSE "Unguarded Physics header")
file(REMOVE "${TEST_DIR}/src/luna/physics/violation.cpp" "${TEST_DIR}/src/luna/physics/unguarded.h")
check_build(TRUE "Restored clean control")
