cmake_minimum_required(VERSION 3.28)

if(NOT IS_DIRECTORY "${ODYSSEUS_SOURCE_ROOT}")
    message(FATAL_ERROR "Architecture include error: source root is missing")
endif()
cmake_path(ABSOLUTE_PATH ODYSSEUS_SOURCE_ROOT NORMALIZE)

function(odysseus_classify path output)
    file(RELATIVE_PATH relative "${ODYSSEUS_SOURCE_ROOT}" "${path}")
    if(relative MATCHES "^core/")
        set(layer core)
    elseif(relative MATCHES "^luna/platform/")
        set(layer platform)
    elseif(relative MATCHES "^luna/engine/")
        set(layer engine)
    elseif(relative MATCHES "^sim/")
        set(layer sim)
    elseif(relative MATCHES "^game/")
        set(layer game)
    else()
        set(layer external)
    endif()
    set(${output} "${layer}" PARENT_SCOPE)
endfunction()

function(odysseus_include_error source header rule)
    message(FATAL_ERROR "Architecture include error: ${source} includes ${header}: ${rule}")
endfunction()

file(GLOB_RECURSE project_files
    "${ODYSSEUS_SOURCE_ROOT}/*.h" "${ODYSSEUS_SOURCE_ROOT}/*.hpp"
    "${ODYSSEUS_SOURCE_ROOT}/*.hh" "${ODYSSEUS_SOURCE_ROOT}/*.hxx"
    "${ODYSSEUS_SOURCE_ROOT}/*.cpp" "${ODYSSEUS_SOURCE_ROOT}/*.cc"
    "${ODYSSEUS_SOURCE_ROOT}/*.cxx")
foreach(source IN LISTS project_files)
    odysseus_classify("${source}" source_layer)
    if(source_layer STREQUAL external)
        odysseus_include_error("${source}" "<source>" "production source is outside the five layers")
    endif()
    set(allowed_core core)
    set(allowed_platform platform core)
    set(allowed_engine engine platform core)
    set(allowed_sim sim core)
    set(allowed_game game engine platform sim core)
    set(allowed "${allowed_${source_layer}}")
    get_filename_component(source_directory "${source}" DIRECTORY)
    file(READ "${source}" content)
    # Join preprocessing continuations, then remove comments before reading directives.
    string(REGEX REPLACE "\\\\\r?\n" "" content "${content}")
    string(REGEX REPLACE "/\\*([^*]|\\*+[^*/])*\\*+/" "" content "${content}")
    string(REGEX REPLACE "//[^\n]*" "" content "${content}")
    file(RELATIVE_PATH source_spelling "${ODYSSEUS_SOURCE_ROOT}" "${source}")
    set(boundary_headers core/boundary.h luna/platform/boundary.h
        luna/engine/boundary.h sim/boundary.h game/boundary.h)
    if(source MATCHES "\\.(h|hpp|hh|hxx)$" AND NOT source_spelling IN_LIST boundary_headers)
        # Require the local boundary before any other include or declaration.
        string(REGEX REPLACE "^[ \t\r\n]*#[ \t]*pragma[ \t]+once" "" header_content "${content}")
        if(NOT header_content MATCHES "^[ \t\r\n]*#[ \t]*include[ \t]+\"boundary\\.h\"")
            odysseus_include_error("${source}" "boundary.h" "every project header must check its own boundary first")
        endif()
    endif()
    # Semicolons are CMake list separators, but irrelevant to include directives.
    string(REPLACE ";" "\\;" content "${content}")
    string(REPLACE "\n" ";" lines "${content}")
    foreach(line IN LISTS lines)
        if(NOT line MATCHES "^[ \t]*#[ \t]*include[ \t]*(.*)$")
            continue()
        endif()
        string(STRIP "${CMAKE_MATCH_1}" directive)
        if(directive MATCHES "^\"([^\"]+)\"[ \t\r]*$")
            set(header "${CMAKE_MATCH_1}")
            set(quoted TRUE)
        elseif(directive MATCHES "^<([^>]+)>[ \t\r]*$")
            set(header "${CMAKE_MATCH_1}")
            set(quoted FALSE)
        else()
            odysseus_include_error("${source}" "${directive}" "macro-expanded or malformed includes cannot be checked")
        endif()
        string(REPLACE "\\" "/" header "${header}")
        string(TOLOWER "${header}" lower_header)
        if(lower_header MATCHES "(^|/)sdl3(/|$)" AND NOT source_layer STREQUAL platform)
            odysseus_include_error("${source}" "${header}" "only Platform may include SDL3")
        endif()
        if(IS_ABSOLUTE "${header}")
            set(destination "${header}")
        elseif(quoted AND EXISTS "${source_directory}/${header}")
            set(destination "${source_directory}/${header}")
        else()
            set(destination "${ODYSSEUS_SOURCE_ROOT}/${header}")
        endif()
        cmake_path(NORMAL_PATH destination)
        if(EXISTS "${destination}")
            file(REAL_PATH "${destination}" destination)
        endif()
        odysseus_classify("${destination}" destination_layer)
        # Ordinary library/standard headers are not members of a project layer.
        if(destination_layer STREQUAL external)
            continue()
        endif()
        if(NOT destination_layer IN_LIST allowed)
            odysseus_include_error("${source}" "${header}" "${source_layer} may not include ${destination_layer}")
        endif()
    endforeach()
endforeach()
